/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 map.glb --types 
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/map-slsg-281dd4989de140ce8916cbac242523a4
Title: Map_slsg
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    road_slsg_01_01_road_slsg_01_0: THREE.Mesh
    road_slsg_01_02_road_slsg_01_0: THREE.Mesh
    road_slsg_01_03_road_slsg_01_0: THREE.Mesh
    road_slsg_01_04_road_slsg_01_0: THREE.Mesh
    road_slsg_02_road_slsg_02_0: THREE.Mesh
    road_slsg_03_01_road_slsg_03_0: THREE.Mesh
    road_slsg_03_02_road_slsg_03_0: THREE.Mesh
    road_slsg_03_03_road_slsg_03_0: THREE.Mesh
    sky_slsg_sky_slsg_0: THREE.Mesh
    slsg_01_01_slsg_01_0: THREE.Mesh
    slsg_01_02_slsg_01_0: THREE.Mesh
    slsg_01_03_slsg_01_0: THREE.Mesh
    slsg_01_04_slsg_01_0: THREE.Mesh
    slsg_01_05_slsg_01_0: THREE.Mesh
    slsg_01_06_slsg_01_0: THREE.Mesh
    slsg_01_07_slsg_01_0: THREE.Mesh
    slsg_01_09_slsg_01_0: THREE.Mesh
    slsg_02_01_slsg_02_0: THREE.Mesh
    slsg_02_02_slsg_02_a_0: THREE.Mesh
    slsg_02_03_slsg_02_a_0: THREE.Mesh
    slsg_02_04_slsg_02_a_0: THREE.Mesh
    slsg_02_05_slsg_02_0: THREE.Mesh
    slsg_02_06_slsg_02_0: THREE.Mesh
    slsg_02_07_slsg_02_a_0: THREE.Mesh
    slsg_02_08_slsg_02_0: THREE.Mesh
    slsg_02_09_slsg_02_0: THREE.Mesh
    slsg_02_10_slsg_02_0: THREE.Mesh
    slsg_02_11_slsg_02_0: THREE.Mesh
    slsg_02_12_slsg_02_a_0: THREE.Mesh
    slsg_02_13_slsg_02_a_0: THREE.Mesh
    slsg_02_14_slsg_02_0: THREE.Mesh
    slsg_02_15_slsg_02_0: THREE.Mesh
    slsg_03_01_slsg_03_0: THREE.Mesh
    slsg_03_02_slsg_03_0: THREE.Mesh
    slsg_03_03_slsg_03_0: THREE.Mesh
    slsg_03_04_slsg_03_0: THREE.Mesh
    slsg_03_05_slsg_03_0: THREE.Mesh
    slsg_03_06_slsg_03_0: THREE.Mesh
    slsg_04_slsg_04_0: THREE.Mesh
    slsg_05_01_slsg_05_a_0: THREE.Mesh
    slsg_05_02_slsg_05_0: THREE.Mesh
    slsg_06_01_slsg_06_0: THREE.Mesh
    slsg_06_02_slsg_06_0: THREE.Mesh
    slsg_06_03_slsg_06_0: THREE.Mesh
    slsg_06_04_slsg_06_0: THREE.Mesh
    slsg_06_05_slsg_06_0: THREE.Mesh
    slsg_06_06_slsg_06_0: THREE.Mesh
    slsg_06_07_slsg_06_0: THREE.Mesh
    slsg_06_08_slsg_06_0: THREE.Mesh
    slsg_06_09_slsg_06_0: THREE.Mesh
    slsg_06_10_slsg_06_0: THREE.Mesh
    slsg_06_11_slsg_06_0: THREE.Mesh
    slsg_07_01_slsg_07_0: THREE.Mesh
    slsg_07_02_slsg_07_0: THREE.Mesh
    slsg_07_03_slsg_07_0: THREE.Mesh
    slsg_07_04_slsg_07_0: THREE.Mesh
    slsg_07_05_slsg_07_0: THREE.Mesh
    mini_map_road_MiniMap_0: THREE.Mesh
    road_slsg_001__0: THREE.Mesh
    slsg_heye_001__0: THREE.Mesh
    slsg_heye_01_slsg_02_a_0: THREE.Mesh
    slsg_toutie_slsg_toutie_0: THREE.Mesh
    Object_143: THREE.SkinnedMesh
    Object_163: THREE.SkinnedMesh
    Object_171: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
    _rootJoint_1: THREE.Bone
    _rootJoint_2: THREE.Bone
  }
  materials: {
    road_slsg_01: THREE.MeshBasicMaterial
    road_slsg_02: THREE.MeshBasicMaterial
    road_slsg_03: THREE.MeshBasicMaterial
    sky_slsg: THREE.MeshBasicMaterial
    slsg_01: THREE.MeshBasicMaterial
    slsg_02: THREE.MeshBasicMaterial
    slsg_02_a: THREE.MeshBasicMaterial
    slsg_03: THREE.MeshBasicMaterial
    slsg_04: THREE.MeshBasicMaterial
    slsg_05_a: THREE.MeshBasicMaterial
    slsg_05: THREE.MeshBasicMaterial
    slsg_06: THREE.MeshBasicMaterial
    slsg_07: THREE.MeshBasicMaterial
    MiniMap: THREE.MeshBasicMaterial
    road_slsg_001__0: THREE.MeshBasicMaterial
    slsg_toutie: THREE.MeshBasicMaterial
    sjfy_06_1: THREE.MeshBasicMaterial
    xrht_yu_01: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/map.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.road_slsg_01_01_road_slsg_01_0.geometry} material={materials.road_slsg_01} />
          <mesh geometry={nodes.road_slsg_01_02_road_slsg_01_0.geometry} material={materials.road_slsg_01} />
          <mesh geometry={nodes.road_slsg_01_03_road_slsg_01_0.geometry} material={materials.road_slsg_01} />
          <mesh geometry={nodes.road_slsg_01_04_road_slsg_01_0.geometry} material={materials.road_slsg_01} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.road_slsg_03_01_road_slsg_03_0.geometry} material={materials.road_slsg_03} />
          <mesh geometry={nodes.road_slsg_03_02_road_slsg_03_0.geometry} material={materials.road_slsg_03} />
          <mesh geometry={nodes.road_slsg_03_03_road_slsg_03_0.geometry} material={materials.road_slsg_03} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.slsg_01_01_slsg_01_0.geometry} material={materials.slsg_01} />
          <mesh geometry={nodes.slsg_01_02_slsg_01_0.geometry} material={materials.slsg_01} />
          <mesh geometry={nodes.slsg_01_03_slsg_01_0.geometry} material={materials.slsg_01} />
          <mesh geometry={nodes.slsg_01_04_slsg_01_0.geometry} material={materials.slsg_01} />
          <mesh geometry={nodes.slsg_01_05_slsg_01_0.geometry} material={materials.slsg_01} />
          <mesh geometry={nodes.slsg_01_06_slsg_01_0.geometry} material={materials.slsg_01} />
          <mesh geometry={nodes.slsg_01_07_slsg_01_0.geometry} material={materials.slsg_01} />
          <mesh geometry={nodes.slsg_01_09_slsg_01_0.geometry} material={materials.slsg_01} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.slsg_02_01_slsg_02_0.geometry} material={materials.slsg_02} />
          <mesh geometry={nodes.slsg_02_02_slsg_02_a_0.geometry} material={materials.slsg_02_a} />
          <mesh geometry={nodes.slsg_02_03_slsg_02_a_0.geometry} material={materials.slsg_02_a} />
          <mesh geometry={nodes.slsg_02_04_slsg_02_a_0.geometry} material={materials.slsg_02_a} />
          <mesh geometry={nodes.slsg_02_05_slsg_02_0.geometry} material={materials.slsg_02} />
          <mesh geometry={nodes.slsg_02_06_slsg_02_0.geometry} material={materials.slsg_02} />
          <mesh geometry={nodes.slsg_02_07_slsg_02_a_0.geometry} material={materials.slsg_02_a} />
          <mesh geometry={nodes.slsg_02_08_slsg_02_0.geometry} material={materials.slsg_02} />
          <mesh geometry={nodes.slsg_02_09_slsg_02_0.geometry} material={materials.slsg_02} />
          <mesh geometry={nodes.slsg_02_10_slsg_02_0.geometry} material={materials.slsg_02} />
          <mesh geometry={nodes.slsg_02_11_slsg_02_0.geometry} material={materials.slsg_02} />
          <mesh geometry={nodes.slsg_02_12_slsg_02_a_0.geometry} material={materials.slsg_02_a} />
          <mesh geometry={nodes.slsg_02_13_slsg_02_a_0.geometry} material={materials.slsg_02_a} />
          <mesh geometry={nodes.slsg_02_14_slsg_02_0.geometry} material={materials.slsg_02} />
          <mesh geometry={nodes.slsg_02_15_slsg_02_0.geometry} material={materials.slsg_02} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.slsg_03_01_slsg_03_0.geometry} material={materials.slsg_03} />
          <mesh geometry={nodes.slsg_03_02_slsg_03_0.geometry} material={materials.slsg_03} />
          <mesh geometry={nodes.slsg_03_03_slsg_03_0.geometry} material={materials.slsg_03} />
          <mesh geometry={nodes.slsg_03_04_slsg_03_0.geometry} material={materials.slsg_03} />
          <mesh geometry={nodes.slsg_03_05_slsg_03_0.geometry} material={materials.slsg_03} />
          <mesh geometry={nodes.slsg_03_06_slsg_03_0.geometry} material={materials.slsg_03} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.slsg_05_01_slsg_05_a_0.geometry} material={materials.slsg_05_a} />
          <mesh geometry={nodes.slsg_05_02_slsg_05_0.geometry} material={materials.slsg_05} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.slsg_06_01_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_02_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_03_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_04_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_05_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_06_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_07_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_08_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_09_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_10_slsg_06_0.geometry} material={materials.slsg_06} />
          <mesh geometry={nodes.slsg_06_11_slsg_06_0.geometry} material={materials.slsg_06} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.slsg_07_01_slsg_07_0.geometry} material={materials.slsg_07} />
          <mesh geometry={nodes.slsg_07_02_slsg_07_0.geometry} material={materials.slsg_07} />
          <mesh geometry={nodes.slsg_07_03_slsg_07_0.geometry} material={materials.slsg_07} />
          <mesh geometry={nodes.slsg_07_04_slsg_07_0.geometry} material={materials.slsg_07} />
          <mesh geometry={nodes.slsg_07_05_slsg_07_0.geometry} material={materials.slsg_07} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.mini_map_road_MiniMap_0.geometry} material={materials.MiniMap} />
          <mesh geometry={nodes.road_slsg_001__0.geometry} material={materials.road_slsg_001__0} />
        </group>
        <group position={[64.97, 27.91, -95.38]} rotation={[Math.PI, -0.716, -Math.PI]} scale={0.6}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_143.geometry} material={materials.sjfy_06_1} skeleton={nodes.Object_143.skeleton} />
        </group>
        <group position={[148.15, -2.9, -207]} rotation={[0, 1.439, 0]} scale={0.428}>
          <primitive object={nodes._rootJoint_1} />
          <skinnedMesh geometry={nodes.Object_163.geometry} material={materials.xrht_yu_01} skeleton={nodes.Object_163.skeleton} />
        </group>
        <group position={[22.85, 16.53, 0.09]} rotation={[0, 0.71, 0]} scale={0.74}>
          <primitive object={nodes._rootJoint_2} />
          <skinnedMesh geometry={nodes.Object_171.geometry} material={materials.sjfy_06_1} skeleton={nodes.Object_171.skeleton} />
        </group>
        <mesh geometry={nodes.road_slsg_02_road_slsg_02_0.geometry} material={materials.road_slsg_02} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.sky_slsg_sky_slsg_0.geometry} material={materials.sky_slsg} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.slsg_04_slsg_04_0.geometry} material={materials.slsg_04} rotation={[-Math.PI / 2, 0, 0]} />
        <group position={[142.03, 1, -64.3]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.slsg_heye_001__0.geometry} material={materials.road_slsg_001__0} />
          <mesh geometry={nodes.slsg_heye_01_slsg_02_a_0.geometry} material={materials.slsg_02_a} />
        </group>
        <mesh geometry={nodes.slsg_toutie_slsg_toutie_0.geometry} material={materials.slsg_toutie} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/map.glb')
